services:
  awesome-website:
    build:
      target: dev
    environment:
      WORDPRESS_DB_HOST: ${AWESOME_WEBSITE_DB_HOST}
      WORDPRESS_DB_USER: ${AWESOME_WEBSITE_DB_USER}
      WORDPRESS_DB_NAME: ${AWESOME_WEBSITE_DB_NAME}
      WORDPRESS_DB_PASSWORD: ${AWESOME_WEBSITE_DB_PASSWORD}
    volumes:
      - type: bind
        source: ./awesome-website/html
        target: /var/www/html
      - type: bind
        source: ./local.ini
        target: /usr/local/etc/php/conf.d/local.ini
    user: ${UID}
    post_start:
      - command: chown -R ${UID}:${GID} /var/www/html
        user: root

  db:
    image: mysql:${AWESOME_MYSQL_VERSION}
    command:
      - "--default-authentication-plugin=mysql_native_password" # Is not necessary for WP 5.4+
      - "--innodb-file-per-table=1"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--max_allowed_packet=64M"
      - "--innodb_buffer_pool_size=1G"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${AWESOME_MYSQL_DATABASE}
      MYSQL_USER: ${AWESOME_MYSQL_USER}
      MYSQL_PASSWORD: ${AWESOME_MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
      # MYSQL_DB_PASSWORD_FILE: /run/secrets/db-root-pass
    volumes:
      - type: volume
        source: database-volume
        target: /var/lib/mysql
      # To load a mysql dump (anyname.sql.gz):
      # - type: bind
      #   source: ./database/docker-entrypoint-initdb.d
      #   target: /docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 1024M
    # secrets:
    #   - db-root-pass
  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_IMAGE_VERSION}
    environment:
      PMA_HOST: ${PHPMYADMIN_HOST}
    ports:
      - mode: ingress
        target: 80
        published: "${PHPMYADMIN_HTTP_PORT}"
        protocol: tcp
    restart: unless-stopped

volumes:
  database-volume:
# secrets:
#   db-root-pass:
#     file: ./awesome-website/db-root-pass.txt
#     environment: AWESOME_MYSQL_ROOT_PASS
